{
  "compatibilityLevel": 1601,
  "model": {
    "annotations": [
      {
        "name": "PBIDesktopVersion",
        "value": "2.132.1053.0 (24.08)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Monitoring Solutions\",\"Monitoring CategoryInfo\",\"Monitoring DetailsInfo\",\"Budget2023_HoursInput\",\"Monitoring Comments\",\"Invoice_Input\",\"Monitoring Invoice\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Budget2023_HoursInput",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"https://solitworkbi.sharepoint.com/sites/Drift/Delte%20dokumenter/Comments%20to%20monitoring%20dashboard.xlsx\" meta [IsParameterQuery=true, Type=\"Any\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "da2fa065-117a-4f24-82a5-ab3bfb309077"
      },
      {
        "name": "Invoice_Input",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"https://solitworkbi.sharepoint.com/sites/Drift-Invoicing/Delte%20dokumenter/Invoicing/Invoicing.xlsx\" meta [IsParameterQuery=true, Type=\"Any\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "e21f3583-dc32-49c4-80f9-fdce95fbc73b"
      }
    ],
    "relationships": [
      {
        "name": "5ce2ba32-d59e-4b2b-8615-11d35fa5d32a",
        "fromColumn": "Solution",
        "fromTable": "Monitoring CategoryInfo",
        "toColumn": "SolutionName",
        "toTable": "Monitoring Solutions"
      },
      {
        "name": "d183563a-c919-403e-ac72-826adccff786",
        "fromColumn": "ID",
        "fromTable": "Monitoring DetailsInfo",
        "toColumn": "ID",
        "toTable": "Monitoring CategoryInfo"
      },
      {
        "name": "64e99951-a45b-4a47-b781-0e62cf4218e1",
        "fromColumn": "SolutionsName",
        "fromTable": "Monitoring Comments",
        "toColumn": "SolutionName",
        "toTable": "Monitoring Solutions"
      },
      {
        "name": "87ddddf2-3090-4744-a5ad-b6ad454970e3",
        "fromColumn": "Update Date",
        "fromTable": "Monitoring Invoice",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_c3b27cf4-d733-487e-92d7-690a71a60449"
      },
      {
        "name": "3420adaa-4beb-4aaa-a0e0-99808a23131a",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "SolutionName",
        "fromTable": "Monitoring Solutions",
        "toColumn": "SolutionName",
        "toTable": "Monitoring Invoice"
      },
      {
        "name": "e6652395-4cac-4b79-98ee-e1f874427784",
        "fromColumn": "SolutionFriendlyName",
        "fromTable": "Monitoring Comments",
        "isActive": false,
        "toColumn": "SolutionFriendlyName",
        "toTable": "Monitoring Invoice"
      }
    ],
    "sourceQueryCulture": "en-GB",
    "tables": [
      {
        "name": "Monitoring Solutions",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Solution_Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "2097917d-f698-4d57-b9dc-0e1a8e7c4190",
            "sourceColumn": "Solution_Id",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          },
          {
            "name": "SolutionName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dfb65925-0623-4f72-a053-edd110684a1d",
            "sourceColumn": "SolutionName",
            "sourceProviderType": "varchar(100)",
            "summarizeBy": "none"
          },
          {
            "name": "SubscriptionId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "06e25be2-5f74-472e-9370-bfb945da056e",
            "sourceColumn": "SubscriptionId",
            "sourceProviderType": "varchar(50)",
            "summarizeBy": "none"
          },
          {
            "name": "TenantId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0f634f4d-2805-4e34-b723-9748251e3447",
            "sourceColumn": "TenantId",
            "sourceProviderType": "varchar(50)",
            "summarizeBy": "none"
          },
          {
            "name": "SolutionType_Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "13d22e58-cccf-4a30-b2a3-3cb9adc25414",
            "sourceColumn": "SolutionType_Id",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          },
          {
            "name": "IsActive",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "a0bdc1e7-5a7a-4997-a584-cbc2b13d9637",
            "sourceColumn": "IsActive",
            "sourceProviderType": "bit",
            "summarizeBy": "none"
          },
          {
            "name": "PrimaryContact",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b5a5a781-a4c7-4b76-a1e8-978b43948774",
            "sourceColumn": "PrimaryContact",
            "sourceProviderType": "varchar(100)",
            "summarizeBy": "none"
          },
          {
            "name": "CheckinTableName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6ece5d2f-bac6-4508-a20d-2106a4e2075f",
            "sourceColumn": "CheckinTableName",
            "sourceProviderType": "varchar(500)",
            "summarizeBy": "none"
          },
          {
            "name": "CheckinInfoTableName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ede5f084-2f2c-431e-9ba0-7dedef9bcc56",
            "sourceColumn": "CheckinInfoTableName",
            "sourceProviderType": "varchar(500)",
            "summarizeBy": "none"
          },
          {
            "name": "CurrentVersion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1983f420-d725-4180-bb0c-bd749b718c7e",
            "sourceColumn": "CurrentVersion",
            "sourceProviderType": "varchar(50)",
            "summarizeBy": "none"
          },
          {
            "name": "ExpectedMonthlyConsumption",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e1e53887-bc8e-4d62-bd2b-f614e54e9056",
            "sourceColumn": "ExpectedMonthlyConsumption",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "SolutionTypeName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "6c4ea0af-8041-45b4-9613-efc340f5c26a",
            "sourceColumn": "SolutionTypeName",
            "sourceProviderType": "varchar(9)",
            "summarizeBy": "none"
          },
          {
            "name": "SolutionFriendlyName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2e662e07-6d12-43df-b65e-8b9892867fec",
            "sourceColumn": "SolutionFriendlyName",
            "sourceProviderType": "varchar(100)",
            "summarizeBy": "none"
          },
          {
            "name": "MonitoredBySupport",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2c235c6f-f8cd-434c-91a7-61505fb22c32",
            "sourceColumn": "MonitoredBySupport",
            "sourceProviderType": "varchar(255)",
            "summarizeBy": "none"
          },
          {
            "name": "ReactOrProactSupport",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "485464d8-7b1a-4580-b154-f95ea33bc578",
            "sourceColumn": "ReactOrProactSupport",
            "sourceProviderType": "varchar(255)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3cd3022a-e1ca-4537-89a3-c22bf3c2ba24",
        "measures": [
          {
            "name": "count_checkinfotablename",
            "expression": "CALCULATE(COUNT('Monitoring Solutions'[SolutionName]), FILTER('Monitoring CategoryInfo', [_sum_of_negatives] <> 0))",
            "formatString": "0",
            "lineageTag": "258a881f-b03e-4999-957c-6c3ab193b3e5"
          },
          {
            "name": "_TESTJET",
            "expression": "IF(MAX('Monitoring Solutions'[SolutionType_Id]) = 1, \"Internal\", IF(MAX('Monitoring Solutions'[SolutionType_Id]) = 2, \"Custommer\", \"Undefined\"))",
            "lineageTag": "80fb0ba5-c3de-44ec-b397-1b66f3db100f"
          },
          {
            "name": "test",
            "expression": "\"test measure\"",
            "lineageTag": "be988385-b30f-4d13-801b-a15596237749"
          }
        ],
        "partitions": [
          {
            "name": "Monitoring Solutions-8868c87d-598f-4166-b0fc-1e87aeab9e23",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Databases(\"sql-afcmonitoring.database.windows.net\"),",
                "    #\"sqldb-afcmonitoring\" = Source{[Name=\"sqldb-afcmonitoring\"]}[Data],",
                "    Monitoring_Solutions = #\"sqldb-afcmonitoring\"{[Schema=\"Monitoring\",Item=\"Solutions\"]}[Data],",
                "    #\"Added Conditional Column\" = Table.AddColumn(Monitoring_Solutions, \"SolutionTypeName\", each if [SolutionType_Id] = 1 then \"Internal\" else if [SolutionType_Id] = 2 then \"Customer\" else \"Undefined\")",
                "in",
                "    #\"Added Conditional Column\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Monitoring CategoryInfo",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "256c8a71-7454-4d92-a67b-17ecad074d8c",
            "sourceColumn": "ID",
            "sourceProviderType": "varchar(500)",
            "summarizeBy": "none"
          },
          {
            "name": "Solution",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d000a6c0-5681-494e-afb9-88d91fda17fa",
            "sourceColumn": "Solution",
            "sourceProviderType": "varchar(200)",
            "summarizeBy": "none"
          },
          {
            "name": "SolutionType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6f481266-9080-41a3-b0e1-5bb485c46be6",
            "sourceColumn": "SolutionType",
            "sourceProviderType": "varchar(50)",
            "summarizeBy": "none"
          },
          {
            "name": "TenantId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8ccd4740-e476-488b-9f75-4533efc805dc",
            "sourceColumn": "TenantId",
            "sourceProviderType": "varchar(50)",
            "summarizeBy": "none"
          },
          {
            "name": "SubscriptionId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c2c337e0-5209-495c-af5e-63e230a97816",
            "sourceColumn": "SubscriptionId",
            "sourceProviderType": "varchar(50)",
            "summarizeBy": "none"
          },
          {
            "name": "DatasetUpdateTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "e3ce04b8-2f9e-41d6-ad0d-3651af12bfe7",
            "sourceColumn": "DatasetUpdateTime",
            "sourceProviderType": "datetime2",
            "summarizeBy": "none"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5c4f3d60-353c-4e8c-8441-2127c3b309ec",
            "sourceColumn": "Category",
            "sourceProviderType": "varchar(100)",
            "summarizeBy": "none"
          },
          {
            "name": "ErrorState",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6e76b487-fc8b-4345-87d4-573cac2c297f",
            "sourceColumn": "ErrorState",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "d59edf43-4073-46d8-afaf-1bee659f4aa8",
        "measures": [
          {
            "name": "_sum_of_negatives",
            "expression": "SUMX('Monitoring CategoryInfo',[_Ranking_solutions])",
            "formatString": "0",
            "lineageTag": "b46a045f-476b-436c-8df0-bc7481ede717"
          },
          {
            "name": "_Count",
            "expression": "COUNTAX('Monitoring CategoryInfo',[_sum_of_negatives] > 0 )",
            "formatString": "0",
            "lineageTag": "1a2a9aa4-49a7-4e70-8498-4d7e632f5495"
          },
          {
            "name": "LastCheckinTime_",
            "expression": [
              "",
              "CALCULATE (",
              "    MAX ( 'Monitoring DetailsInfo'[InfoValue] ),",
              "    FILTER (",
              "        'Monitoring DetailsInfo',",
              "        'Monitoring DetailsInfo'[InfoType] = \"LastCheckinTime\"",
              "    )",
              ")"
            ],
            "lineageTag": "ef591c1c-2c90-4742-8e13-41da5948235a"
          }
        ],
        "partitions": [
          {
            "name": "Monitoring CategoryInfo-0ea0f023-047f-4cdc-ae0a-5b31899baafa",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Databases(\"sql-afcmonitoring.database.windows.net\"),",
                "    #\"sqldb-afcmonitoring\" = Source{[Name=\"sqldb-afcmonitoring\"]}[Data],",
                "    Monitoring_CategoryInfo = #\"sqldb-afcmonitoring\"{[Schema=\"Monitoring\",Item=\"CategoryInfo\"]}[Data]",
                "in",
                "    Monitoring_CategoryInfo"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Monitoring DetailsInfo",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "22bc76ea-b72e-46a2-b379-8d0a112863bd",
            "sourceColumn": "ID",
            "sourceProviderType": "varchar(500)",
            "summarizeBy": "none"
          },
          {
            "name": "Solution",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "78f47065-b827-4ebf-9755-c9aafb60b148",
            "sourceColumn": "Solution",
            "sourceProviderType": "varchar(200)",
            "summarizeBy": "none"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "43f7c004-a7a2-4fc3-8d0d-366054dfa8da",
            "sourceColumn": "Category",
            "sourceProviderType": "varchar(100)",
            "summarizeBy": "none"
          },
          {
            "name": "InfoType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a2d68836-14d3-488e-b655-7ae7e6555592",
            "sourceColumn": "InfoType",
            "sourceProviderType": "varchar(100)",
            "summarizeBy": "none"
          },
          {
            "name": "InfoName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b43e7978-7f5b-4c01-bce0-a55e02ed6d82",
            "sourceColumn": "InfoName",
            "sourceProviderType": "varchar(100)",
            "summarizeBy": "none"
          },
          {
            "name": "InfoValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "223c8fb1-5609-437b-94db-49ec30efd3d9",
            "sourceColumn": "InfoValue",
            "sourceProviderType": "varchar(100)",
            "summarizeBy": "none"
          },
          {
            "name": "ErrorState",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8872c85d-6fca-4a72-bcff-393a0e06677b",
            "sourceColumn": "ErrorState",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "InfoDescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f46ec6da-d80a-4659-8b26-491fa46e7b9f",
            "sourceColumn": "InfoDescription",
            "sourceProviderType": "varchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "InfoEventTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "7a667bdf-c73c-4d33-a472-9e8a6ec7591b",
            "sourceColumn": "InfoEventTime",
            "sourceProviderType": "datetime2",
            "summarizeBy": "none"
          },
          {
            "name": "HasAccess",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2a90c8b4-32c7-4e88-a8a8-5f30140fe204",
            "sourceColumn": "HasAccess",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "DataUpdatedTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "1f297c91-d9f3-4915-aa0f-f296923916c1",
            "sourceColumn": "DataUpdatedTime",
            "sourceProviderType": "datetime2",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "74e24965-c174-4144-a2bf-58b5253a7a03",
        "measures": [
          {
            "name": "_Count_Amount_of_errors",
            "expression": "CALCULATE(COUNTROWS('Monitoring DetailsInfo'), 'Monitoring DetailsInfo'[ErrorState] <> 1)",
            "formatString": "0",
            "lineageTag": "6950a8de-5c2c-4a89-b8d9-09a302e2830a"
          },
          {
            "name": "Count_distinct_infortype",
            "expression": "DISTINCTCOUNT('Monitoring DetailsInfo'[InfoType])",
            "formatString": "0",
            "lineageTag": "8ffc36c7-cee3-4cc5-9086-4360f2ec4647"
          },
          {
            "name": "dummy",
            "expression": "1",
            "formatString": "0",
            "lineageTag": "7b3c65b8-431c-474a-871d-3df510c1c4ec"
          },
          {
            "name": "_Label_details_solutionname",
            "expression": "CONCATENATE( \"Error details for: \" , MAX('Monitoring DetailsInfo'[Solution])) ",
            "lineageTag": "b673335f-131d-4b70-a9c5-ed9e9dd24e8e"
          },
          {
            "name": "Label_error_state",
            "expression": "\"‎‎‎‎‎‎‎ Error state range: [\" & MIN('Monitoring DetailsInfo'[ErrorState]) & \"  :  \" &MAX('Monitoring DetailsInfo'[ErrorState]) & \"]\"",
            "lineageTag": "8116a9bb-ff3f-4fc4-bc8a-7691015f5ad7"
          },
          {
            "name": "_Count_Errors_BI_Framework_Tabular",
            "expression": [
              "",
              "VAR Result = MAX(CALCULATE(COUNTROWS('Monitoring DetailsInfo'), 'Monitoring DetailsInfo'[ErrorState] <> 1,'Monitoring DetailsInfo'[Category] = \"BI Framework Tabular\"),0)",
              "Return IF(Result = 0, BLANK(), Result)"
            ],
            "formatString": "0",
            "lineageTag": "ecd1b7bd-3384-4d39-ad32-8ab720f1b063"
          },
          {
            "name": "_Ranking_solutions",
            "expression": [
              "",
              "VAR result =",
              "    IF (",
              "        [_Colour_Errors_Platform] = 2,",
              "        10,",
              "        IF (",
              "            [_Colour_Errors_Platform] = 1,",
              "            9,",
              "            IF (",
              "                [_Colour_Errors_Job_Agent] = 2,",
              "                8,",
              "                IF (",
              "                    [_Colour_Errors_Job_Agent] = 1,",
              "                    7,",
              "                    IF (",
              "                        [_Colour_Errors_Data_Platform] = 2,",
              "                        6,",
              "                        IF (",
              "                            [_Colour_Errors_Data_Platform] = 1,",
              "                            5,",
              "                            IF (",
              "                                [_Colour_Errors_BI_Framework_SQL] = 2,",
              "                                4,",
              "                                IF (",
              "                                    [_Colour_Errors_BI_Framework_SQL] = 1,",
              "                                    3,",
              "                                    IF (",
              "                                        [_Colour_Errors_BI_Framework_Tabular] = 2,",
              "                                        2,",
              "                                        IF ( [_Colour_Errors_BI_Framework_Tabular] = 1, 1, 0 )",
              "                                    )",
              "                                )",
              "                            )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )",
              "RETURN",
              " IF(Result = 0, BLANK(), Result)"
            ],
            "formatString": "0",
            "lineageTag": "3629d392-f915-415b-ad66-bdd9ca9d3dbd"
          },
          {
            "name": "_Count_Errors_BI_Framework_SQL",
            "expression": [
              "",
              "VAR Result = MAX(CALCULATE(COUNTROWS('Monitoring DetailsInfo'), 'Monitoring DetailsInfo'[ErrorState] <> 1,'Monitoring DetailsInfo'[Category] = \"BI Framework SQL\"),0)",
              "Return IF(Result = 0, BLANK(), Result)"
            ],
            "formatString": "0",
            "lineageTag": "72a4c420-139c-40e9-a605-cc6cfe6622ce"
          },
          {
            "name": "_Count_Errors_Data_Platform",
            "expression": [
              "",
              "VAR Result = MAX(CALCULATE(COUNTROWS('Monitoring DetailsInfo'), 'Monitoring DetailsInfo'[ErrorState] <> 1,'Monitoring DetailsInfo'[Category] = \"Data Platform\"),0)",
              "Return IF(Result = 0, BLANK(), Result)"
            ],
            "formatString": "0",
            "lineageTag": "17428e03-a3e3-441e-adf8-b38d96b40f2d"
          },
          {
            "name": "_Count_Errors_Job_Agent",
            "expression": [
              "",
              "VAR Result = MAX(CALCULATE(COUNTROWS('Monitoring DetailsInfo'), 'Monitoring DetailsInfo'[ErrorState] <> 1,'Monitoring DetailsInfo'[Category] = \"Job Agent\"),0)",
              "Return IF(Result = 0, BLANK(), Result)"
            ],
            "formatString": "0",
            "lineageTag": "10a2427f-c52f-467d-a58d-ab4a9be38f9b"
          },
          {
            "name": "_Count_Errors_Platform",
            "expression": [
              "",
              "VAR Result = MAX(CALCULATE(COUNTROWS('Monitoring DetailsInfo'), 'Monitoring DetailsInfo'[ErrorState] <> 1,'Monitoring DetailsInfo'[Category] = \"Platform\"),0)",
              "",
              "Return IF(Result = 0, BLANK(), Result)",
              "",
              ""
            ],
            "formatString": "0",
            "lineageTag": "c3835b63-d232-4e0d-b50c-66ac15414569"
          },
          {
            "name": "_Colour_Errors_Platform",
            "expression": [
              "",
              "VAR Warning = MAX(CALCULATE(COUNTROWS('Monitoring DetailsInfo'), 'Monitoring DetailsInfo'[ErrorState] = -1,'Monitoring DetailsInfo'[Category] = \"Platform\"),0)",
              "VAR Caution = MAX(CALCULATE(COUNTROWS('Monitoring DetailsInfo'), 'Monitoring DetailsInfo'[ErrorState] = 0,'Monitoring DetailsInfo'[Category] = \"Platform\"),0)",
              "Return ",
              "",
              "IF(Warning > 0, 2, IF(Caution > 0,1,0))"
            ],
            "formatString": "0",
            "lineageTag": "9a293cd3-6b5d-4d44-9664-7e4bf64abaa2"
          },
          {
            "name": "_Colour_Errors_BI_Framework_SQL",
            "expression": [
              "",
              "VAR Warning = MAX(CALCULATE(COUNTROWS('Monitoring DetailsInfo'), 'Monitoring DetailsInfo'[ErrorState] = -1,'Monitoring DetailsInfo'[Category] = \"BI Framework SQL\"),0)",
              "VAR Caution = MAX(CALCULATE(COUNTROWS('Monitoring DetailsInfo'), 'Monitoring DetailsInfo'[ErrorState] = 0,'Monitoring DetailsInfo'[Category] = \"BI Framework SQL\"),0)",
              "Return ",
              "",
              "IF(Warning > 0, 2, IF(Caution > 0,1,0))"
            ],
            "formatString": "0",
            "lineageTag": "71cea048-0624-4e90-92a9-f4216cf3654f"
          },
          {
            "name": "_Colour_Errors_BI_Framework_Tabular",
            "expression": [
              "",
              "VAR Warning = MAX(CALCULATE(COUNTROWS('Monitoring DetailsInfo'), 'Monitoring DetailsInfo'[ErrorState] = -1,'Monitoring DetailsInfo'[Category] = \"BI Framework Tabular\"),0)",
              "VAR Caution = MAX(CALCULATE(COUNTROWS('Monitoring DetailsInfo'), 'Monitoring DetailsInfo'[ErrorState] = 0,'Monitoring DetailsInfo'[Category] = \"BI Framework Tabular\"),0)",
              "Return ",
              "",
              "IF(Warning > 0, 2, IF(Caution > 0,1,0))"
            ],
            "formatString": "0",
            "lineageTag": "1e8cb7aa-4223-458f-bdbf-aa7fe33c73bb"
          },
          {
            "name": "_Colour_Errors_Data_Platform",
            "expression": [
              "",
              "VAR Warning = MAX(CALCULATE(COUNTROWS('Monitoring DetailsInfo'), 'Monitoring DetailsInfo'[ErrorState] = -1,'Monitoring DetailsInfo'[Category] = \"Data Platform\"),0)",
              "VAR Caution = MAX(CALCULATE(COUNTROWS('Monitoring DetailsInfo'), 'Monitoring DetailsInfo'[ErrorState] = 0,'Monitoring DetailsInfo'[Category] = \"Data Platform\"),0)",
              "Return ",
              "",
              "IF(Warning > 0, 2, IF(Caution > 0,1,0))"
            ],
            "formatString": "0",
            "lineageTag": "d19d7785-ae74-41f6-9fc0-13ce965953c4"
          },
          {
            "name": "_Colour_Errors_Job_Agent",
            "expression": [
              "",
              "VAR Warning = MAX(CALCULATE(COUNTROWS('Monitoring DetailsInfo'), 'Monitoring DetailsInfo'[ErrorState] = -1,'Monitoring DetailsInfo'[Category] = \"Job Agent\"),0)",
              "VAR Caution = MAX(CALCULATE(COUNTROWS('Monitoring DetailsInfo'), 'Monitoring DetailsInfo'[ErrorState] = 0,'Monitoring DetailsInfo'[Category] = \"Job Agent\"),0)",
              "Return ",
              "",
              "IF(Warning > 0, 2, IF(Caution > 0,1,0))"
            ],
            "formatString": "0",
            "lineageTag": "9f5fe578-af60-42ed-bf94-99bba68c2eb8"
          },
          {
            "name": "_Label_details_date",
            "expression": [
              "",
              "CONCATENATE (",
              "    \"Dataset update time: \",",
              "    FORMAT (",
              "        CALCULATE (",
              "            MAX ( 'Monitoring DetailsInfo'[InfoValue] ),",
              "            ALL ( 'Monitoring DetailsInfo'[ErrorState] ),",
              "            ALL ( 'Monitoring CategoryInfo'[ErrorState] ),",
              "            'Monitoring DetailsInfo'[InfoType] = \"LastCheckinTime\"",
              "        ),",
              "        \"dd/MM/YYYY - hh:mm:ss\"",
              "    )",
              ")",
              ""
            ],
            "lineageTag": "3bd4154a-34f8-49f3-934f-d8b6843aa6d7"
          },
          {
            "name": "_AAAA_Count",
            "expression": [
              "",
              "--DISTINCTCOUNT('Monitoring DetailsInfo'[Solution])",
              " CALCULATE(COUNT('Monitoring DetailsInfo'[InfoType]),'Monitoring DetailsInfo'[InfoType] = \"SqlMetrics - DTU percentage\")"
            ],
            "formatString": "0",
            "lineageTag": "1ae90587-d256-48c3-9524-ee65cd332c49"
          },
          {
            "name": "percentagelabel",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "MAX(CALCULATE(VALUE(SELECTEDVALUE('Monitoring DetailsInfo'[InfoValue]))/100,'Monitoring DetailsInfo'[InfoType] = \"SqlMetrics - DTU percentage\"),0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "6d881523-3314-4817-b705-7220e9ba1df7"
          },
          {
            "name": "__TESTJET",
            "lineageTag": "cf77dbf1-71b6-4002-b80e-16157dbb3fc9"
          },
          {
            "name": "_Colour_Ranking_Solutions",
            "expression": [
              "",
              "MAXX(",
              "    {",
              "        'Monitoring DetailsInfo'[_Colour_Errors_Platform],",
              "        'Monitoring DetailsInfo'[_Colour_Errors_Job_Agent],",
              "        'Monitoring DetailsInfo'[_Colour_Errors_Data_Platform],",
              "        'Monitoring DetailsInfo'[_Colour_Errors_BI_Framework_SQL],",
              "        'Monitoring DetailsInfo'[_Colour_Errors_BI_Framework_tabular]",
              "    },",
              "    [Value]",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "aa8d193e-2e3e-4bd3-ba3e-756a33c0f152"
          },
          {
            "name": "_Label_overview_date",
            "expression": "CONCATENATE( \"Oldest dataset update time: \" , FORMAT(Min('Monitoring CategoryInfo'[DatasetUpdateTime]), \"dd/MM/YYYY - hh:mm:ss\"))",
            "lineageTag": "b3b5d707-8ada-4cd3-ba3c-9937877ab7ab"
          },
          {
            "name": "MW_MostRecentLogin_InfoValue",
            "expression": [
              "",
              "CALCULATE(",
              "    SELECTEDVALUE('Monitoring DetailsInfo'[InfoValue], BLANK()),",
              "    FILTER(",
              "        'Monitoring DetailsInfo',",
              "        'Monitoring DetailsInfo'[InfoName] = \"LatestUserLogin\"",
              "    )",
              ")"
            ],
            "lineageTag": "4fa8fa4d-30a1-4367-849c-ca9c1ea5ed98"
          },
          {
            "name": "MW_MostRecentLogin_InfoDescription",
            "expression": [
              "",
              "CALCULATE(MIN('Monitoring DetailsInfo'[InfoDescription]), 'Monitoring DetailsInfo'[InfoName]=\"LatestUserLogin\")"
            ],
            "lineageTag": "5ba84c6a-d326-4a0a-a8e1-645653f26a2b"
          },
          {
            "name": "MW_MostLogins_InfoDescription",
            "expression": [
              "",
              "CALCULATE(MIN('Monitoring DetailsInfo'[InfoDescription]), 'Monitoring DetailsInfo'[InfoName]=\"UserLoginsLastWeek\")"
            ],
            "lineageTag": "c00e2b57-9b45-4c95-be57-f252d3ca09e5"
          },
          {
            "name": "MW_MostLogins_InfoValue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SUMX (",
              "    FILTER (",
              "        'Monitoring DetailsInfo',[InfoName] = \"UserLoginsLastWeek\"",
              "    ),",
              "    VALUE ( 'Monitoring DetailsInfo'[InfoValue] )",
              ")",
              ""
            ],
            "lineageTag": "ac8f231b-ed02-44b5-9695-1e528bf54e8d"
          },
          {
            "name": "MW_MostConsumptionLM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    SUMX (",
              "        FILTER (",
              "            'Monitoring DetailsInfo',",
              "            [InfoType] = \"ConsumptionInfo_LastMonth\"",
              "                && [InfoName] = \"Total\"",
              "        ),",
              "        VALUE ( 'Monitoring DetailsInfo'[InfoValue] )",
              "    )"
            ],
            "lineageTag": "a4f5a2fe-c033-4b53-9a1c-2039ccf54397"
          },
          {
            "name": "MW_MostConsumptionMTD_Actual",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SUMX (",
              "    FILTER (",
              "        'Monitoring DetailsInfo',",
              "        'Monitoring DetailsInfo'[InfoType] = \"ConsumptionInfo_MonthToDate_Forecast\"",
              "    ),",
              "    IF (",
              "        CONTAINSSTRING ( 'Monitoring DetailsInfo'[InfoName], \"Actual\" ),",
              "        VALUE('Monitoring DetailsInfo'[InfoValue]),",
              "        BLANK()",
              "    )",
              ")"
            ],
            "lineageTag": "1f087008-2ffe-49f6-a7bc-bf229a14c3b3"
          },
          {
            "name": "MW_MostConsumptionMTD_Forecast",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SUMX (",
              "    FILTER (",
              "        'Monitoring DetailsInfo',",
              "        'Monitoring DetailsInfo'[InfoType] = \"ConsumptionInfo_MonthToDate_Forecast\"",
              "    ),",
              "    IF (",
              "        CONTAINSSTRING ( 'Monitoring DetailsInfo'[InfoName], \"Forecast\" ),",
              "        VALUE('Monitoring DetailsInfo'[InfoValue]),",
              "        BLANK()",
              "    )",
              ")"
            ],
            "lineageTag": "15c96ec4-c128-44ad-ac10-f6ff3d53dd39"
          },
          {
            "name": "MW_MostConsumptionEOM_Forecast",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "[MW_MostConsumptionMTD_Actual]+[MW_MostConsumptionMTD_Forecast]"
            ],
            "lineageTag": "f68b7dbc-11b9-48c4-8d7c-cdd3c6142210"
          },
          {
            "name": "MW_MostExpectedMonthlyConsumption",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SUM('Monitoring Solutions'[ExpectedMonthlyConsumption])"
            ],
            "formatString": "#,0",
            "lineageTag": "7edf99de-9ba6-4293-b999-04f0d1fa1b2f"
          },
          {
            "name": "MW_%InvoiceSpent",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "DIVIDE(",
              "[MW_MostConsumptionLM], 'Monitoring DetailsInfo'[MW_MostExpectedMonthlyConsumption])"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "081dbcaf-2559-44ff-90e0-224372f88d8e"
          },
          {
            "name": "percentagelabel_cube",
            "expression": "MAX(CALCULATE(VALUE(LEFT(SELECTEDVALUE('Monitoring DetailsInfo'[InfoValue]),2)),'Monitoring DetailsInfo'[InfoType] = \"TabularMetrics - Memory Percentage\"),0)/100",
            "formatString": "0%;-0%;0%",
            "lineageTag": "a70e1cbb-3874-4844-8165-5c13f79bd76a"
          },
          {
            "name": "MW_CostEOMRelativeToLM",
            "expression": "[MW_MostConsumptionEOM_Forecast] / [MW_MostConsumptionLM] - 1",
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "1141e008-cbce-45f7-9ed7-7262f4b2c407"
          },
          {
            "name": "_TEST_MW_MostConsumptionLM_Kirkbi",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR calc = CALCULATE(SUMX( ",
              "        FILTER (",
              "            'Monitoring DetailsInfo',",
              "            [InfoType] = \"ConsumptionInfo_LastMonth\"",
              "                && [InfoName] = \"Total\"",
              "        ),",
              "        VALUE ( 'Monitoring DetailsInfo'[InfoValue] )",
              "    ), ALL('Monitoring Solutions'), 'Monitoring solutions'[SolutionFriendlyName] in {\"Kirkbi\", \"Kirkby - Family Office\", \"Kirkby - Lego Fonden\"})",
              "RETURN",
              "calc"
            ],
            "lineageTag": "ba9751db-cae6-4485-903b-b82c22339297"
          },
          {
            "name": "_TEST_MW_MostConsumptionLM_Total",
            "expression": [
              "",
              "IF(CONTAINSSTRING(MAX('Monitoring Solutions'[SolutionFriendlyName]), \"Kirk\"), ",
              "CALCULATE(SUMX( ",
              "        FILTER (",
              "            'Monitoring DetailsInfo',",
              "            [InfoType] = \"ConsumptionInfo_LastMonth\"",
              "                && [InfoName] = \"Total\"",
              "        ),",
              "        VALUE ( 'Monitoring DetailsInfo'[InfoValue] )",
              "    ), ALL('Monitoring Solutions'), 'Monitoring solutions'[SolutionFriendlyName] in {\"Kirkbi\", \"Kirkby - Family Office\", \"Kirkby - Lego Fonden\"}), ",
              "    SUMX (",
              "        FILTER (",
              "            'Monitoring DetailsInfo',",
              "            [InfoType] = \"ConsumptionInfo_LastMonth\"",
              "                && [InfoName] = \"Total\"",
              "        ),",
              "        VALUE ( 'Monitoring DetailsInfo'[InfoValue] )",
              "    ))"
            ],
            "formatString": "#,0",
            "lineageTag": "56a74c64-ea64-42d2-be9a-9fb5680e4685"
          },
          {
            "name": "MW_NoLoginsLastMonth",
            "expression": [
              "",
              "CALCULATE(",
              "    SELECTEDVALUE('Monitoring DetailsInfo'[InfoDescription], BLANK()),",
              "    FILTER(",
              "        'Monitoring DetailsInfo',",
              "        'Monitoring DetailsInfo'[InfoValue] = BLANK()",
              "    )",
              ")"
            ],
            "lineageTag": "d0cc6327-d20e-4af8-a48b-7794ef508668"
          },
          {
            "name": "Activity_NoLoginsMonthCount",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNT('Monitoring DetailsInfo'[Solution]),",
              "    'Monitoring DetailsInfo'[InfoValue] = BLANK()",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "4ace416b-5897-4030-8d36-afe45e580b73"
          },
          {
            "name": "Activity_LoginsLastWeekCount",
            "expression": [
              "",
              "",
              "VAR calc =",
              "    CALCULATE(",
              "        COUNT('Monitoring DetailsInfo'[Solution]),",
              "        'Monitoring DetailsInfo'[InfoName] = \"UserLoginsLastWeek\",",
              "        VALUE('Monitoring DetailsInfo'[InfoValue]) < 10",
              "    )",
              "RETURN",
              "calc",
              "",
              ""
            ],
            "formatString": "0",
            "lineageTag": "83068639-056e-44af-88a1-a12a2f214417"
          },
          {
            "name": "MW_NoLoginsLastMonthBool",
            "expression": [
              "",
              "IF([MW_NoLoginsLastMonth] = BLANK(), \"True\", \"False\")"
            ],
            "lineageTag": "b608b66c-7813-43cf-95d1-62dd7e70020c"
          },
          {
            "name": "DataUpdatedLatestUserLogin",
            "expression": [
              "",
              "",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            'Monitoring DetailsInfo', ",
              "            'Monitoring DetailsInfo'[InfoName] = \"LatestUserLogin\"",
              "        ), ",
              "        'Monitoring DetailsInfo'[DataUpdatedTime]",
              "    ),",
              "    'Monitoring DetailsInfo'[DataUpdatedTime]",
              ")"
            ],
            "formatString": "General Date",
            "lineageTag": "1a3540c9-a797-45b8-8dbd-097b67123610"
          }
        ],
        "partitions": [
          {
            "name": "Monitoring DetailsInfo-844d1053-b0ef-4e9b-a5ef-f2f22c366365",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Databases(\"sql-afcmonitoring.database.windows.net\"),",
                "    #\"sqldb-afcmonitoring\" = Source{[Name=\"sqldb-afcmonitoring\"]}[Data],",
                "    Monitoring_DetailsInfo = #\"sqldb-afcmonitoring\"{[Schema=\"Monitoring\",Item=\"DetailsInfo\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Monitoring_DetailsInfo,{{\"DataUpdatedTime\", type datetime}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_81b07a6e-1ffc-4f01-a41d-f4fc9be73250",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "47b7aa13-2d05-4fd4-953e-bfdf92558338",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "e20129b8-d95d-430c-b05f-a37e5517714b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f560d77c-9b4b-4a71-a02a-7f8a22a31ef6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "68adb3a4-1999-4322-8b92-cfc9f2f05134",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "235c2b8d-fd18-41d2-b5d2-6bb978d07634",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "374feb7e-7c00-4ce7-968b-641bcb5aceca",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "565dcd23-ba36-4930-8b64-d78fdccdc8b0",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "06b0d9d7-c8fc-45e6-975f-879a692d088f",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "fd3f41ab-29ed-45dd-b22c-88374dc67c36",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "e4b48ec3-06ff-4d88-bb4f-2238194e40e6",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "7eb752a4-2114-46d3-80e2-1b4d7ea8806e",
                "ordinal": 3
              }
            ],
            "lineageTag": "a58e247d-e7e1-4991-baa7-34db01abb147"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "79025e84-ec85-4f70-8325-6520b854d50e",
        "partitions": [
          {
            "name": "DateTableTemplate_81b07a6e-1ffc-4f01-a41d-f4fc9be73250",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Monitoring Comments",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "SolutionsName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "46c999b1-68f4-4ca6-975d-94c21e95c5f0",
            "sourceColumn": "SolutionsName",
            "summarizeBy": "none"
          },
          {
            "name": "SolutionFriendlyName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c8b4efa6-0ee9-4258-a49b-812fba7825ba",
            "sourceColumn": "SolutionFriendlyName",
            "summarizeBy": "none"
          },
          {
            "name": "Comment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f4ebe666-5c8d-4bad-837c-c3d5d2ebfc93",
            "sourceColumn": "Comment",
            "summarizeBy": "none"
          },
          {
            "name": "Comment Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9eafe844-642b-42fe-8aac-21b4983ecb1b",
            "sourceColumn": "Comment Date",
            "summarizeBy": "none"
          },
          {
            "name": "Author of comment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ed95ffd5-951f-42e4-a791-1014cee48be0",
            "sourceColumn": "Author of comment",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a090ec59-eb02-4625-8fed-3864b8070828",
        "partitions": [
          {
            "name": "Monitoring Comments",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(Web.Contents(Budget2023_HoursInput), null, true),",
                "    #\"Expanded Data\" = Table.ExpandTableColumn(Source, \"Data\", {\"Column1\", \"Column2\", \"Column3\", \"Column4\", \"Column5\"}, {\"Data.Column1\", \"Data.Column2\", \"Data.Column3\", \"Data.Column4\", \"Data.Column5\"}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Expanded Data\", [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Sheet1\", type text}, {\"SolutionsName\", type text}, {\"SolutionFriendlyName\", type any}, {\"Comment\", type any}, {\"Comment Date\", type any}, {\"Author of comment\", type any}, {\"Sheet1_1\", type text}, {\"Sheet\", type text}, {\"false\", type logical}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Sheet1\", \"Sheet1_1\", \"Sheet\", \"false\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Monitoring Invoice",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "SolutionName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "86f511df-698e-4815-a3ec-f21deddac6f8",
            "sourceColumn": "SolutionName",
            "summarizeBy": "none"
          },
          {
            "name": "Invoiced DKK - monthly",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "5c73a96b-883b-4cd7-8dd2-bd7ffde6e53e",
            "sourceColumn": "Invoiced DKK - monthly",
            "summarizeBy": "sum"
          },
          {
            "name": "Billing Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d90c6f12-295e-4975-a8ad-09be72c96ca5",
            "sourceColumn": "Billing Date",
            "summarizeBy": "none"
          },
          {
            "name": "Update Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "41c382ec-01bd-441c-9cb6-7f99e1d9534b",
            "sourceColumn": "Update Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_c3b27cf4-d733-487e-92d7-690a71a60449"
                },
                "isDefault": true,
                "relationship": "87ddddf2-3090-4744-a5ad-b6ad454970e3"
              }
            ]
          },
          {
            "name": "Update Author",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0d18c1ac-9ca2-408b-a400-de959129d3eb",
            "sourceColumn": "Update Author",
            "summarizeBy": "none"
          },
          {
            "name": "InvoiceVsLM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": [
              "--Represents how much the LM costs exceeds the monthly invoice. ",
              "-- Uses if statement to check for blank data as the data source updates and wipes data regularly",
              "IF(",
              "    OR(",
              "        ISBLANK([Invoiced DKK - monthly]), ",
              "        ISBLANK([MW_MostConsumptionLM])",
              "    ), ",
              "    BLANK(), ",
              "    [MW_MostConsumptionLM] - [Invoiced DKK - monthly]",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "50d17cae-0d1f-4466-a44f-36d3da63c428",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "InvoiceVsForecast",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": [
              "--Represents how much the ForecastEOM costs exceeds the monthly invoice. ",
              "-- Uses if statement to check for blank data as the data source updates and wipes data regularly",
              "IF(",
              "    OR(",
              "        ISBLANK([Invoiced DKK - monthly]), ",
              "        ISBLANK([MW_MostConsumptionEOM_Forecast])",
              "    ), ",
              "    BLANK(), ",
              "    [MW_MostConsumptionEOM_Forecast] - [Invoiced DKK - monthly]",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "e02c4950-58d3-4fa4-8a20-e5cc5c1f858e",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "InvoiceLoaded",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "--Used to filter the solutions that have available data on invoice and if the solution has loaded forecast and lm data ",
              "IF(",
              "    OR(",
              "        ISBLANK([Invoiced DKK - monthly]), ",
              "        ISBLANK([SolutionLoaded])",
              "    ), ",
              "    BLANK(), ",
              "    [Invoiced DKK - monthly]",
              ")"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "b62be6da-b22d-44f4-98ec-f2322b8c02c4",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "SolutionLoaded",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "--Used to filter the solutions extracted from the database ",
              "IF(",
              "    OR(",
              "        ISBLANK([Invoiced DKK - monthly]), ",
              "        ISBLANK([MW_MostConsumptionEOM_Forecast])",
              "    ), ",
              "    BLANK(), ",
              "    [SolutionParentName]",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "b1911fab-2f7a-4f62-b3de-3cd40c94727f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "ForecastLoaded",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "dataType": "double",
            "expression": [
              "--Used to filter the solutions that have available data on forecast and if the solution has loaded forecast and lm data ",
              "IF(",
              "    OR(",
              "        ISBLANK([MW_MostConsumptionEOM_Forecast]), ",
              "        ISBLANK([SolutionLoaded])",
              "    ), ",
              "    BLANK(), ",
              "    [MW_MostConsumptionEOM_Forecast]",
              ")"
            ],
            "formatString": "#,0",
            "isDataTypeInferred": true,
            "lineageTag": "6c6afc53-6313-43e8-b41a-d42226c9ec19",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "LastMonthLoaded",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": [
              "--Used to filter the solutions that have available data on forecast and if the solution has loaded forecast and lm data ",
              "",
              "IF(",
              "    OR(",
              "        ISBLANK([MW_MostConsumptionLM]), ",
              "        ISBLANK([SolutionLoaded])",
              "    ), ",
              "    BLANK(), ",
              "    [MW_MostConsumptionLM]",
              ")",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "67941565-58c4-4d00-a210-ac7759f35374",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "ForecastLoadedResultCol",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "[InvoiceLoadedSum] - [ForecastLoadedSum]",
            "isDataTypeInferred": true,
            "lineageTag": "89950c52-2eef-4b72-81a2-f8ce264483fd",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "ForecastLoadedResultPercCol",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "expression": "[ForecastLoadedResult] / [InvoiceLoadedSum]",
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "isDataTypeInferred": true,
            "lineageTag": "2de780f9-f27a-4b39-9a5a-b022dcb4bcad",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Sorting_column",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF(",
              "    NOT(ISBLANK([MW_MostConsumptionLM])),",
              "    \"Last Month\",",
              "    IF(",
              "        NOT(ISBLANK([MW_MostConsumptionEOM_Forecast])),",
              "        \"EOM\",",
              "        BLANK()",
              "    )",
              ")",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "9b673d9c-01db-4826-ae35-9125b97f2f2e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Tenant",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0d924cce-f2c4-4a7c-ae63-96c00b6095d2",
            "sourceColumn": "Tenant",
            "summarizeBy": "none"
          },
          {
            "name": "SolutionID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "986eee03-eae9-435b-84c0-278f3b2ff79e",
            "sourceColumn": "SolutionID",
            "summarizeBy": "count"
          },
          {
            "name": "Client",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f2e167f8-e990-49c3-939c-69bddc78f571",
            "sourceColumn": "Client",
            "summarizeBy": "none"
          },
          {
            "name": "SolutionFriendlyName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4d159a03-ed01-48b6-b4a1-e36e99a64a4b",
            "sourceColumn": "SolutionFriendlyName",
            "summarizeBy": "none"
          },
          {
            "name": "SolutionParentName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a328c1c5-3cd9-43a7-b171-3472345ea4a3",
            "sourceColumn": "SolutionParentName",
            "summarizeBy": "none"
          },
          {
            "name": "Comments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a669a0f7-4289-4699-a8f8-c6284899f4b7",
            "sourceColumn": "Comments",
            "summarizeBy": "none"
          },
          {
            "name": "_TEST_LM_Cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "SUMX('Monitoring Invoice',",
              "    'Monitoring DetailsInfo'[MW_MostConsumptionLM]",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "a2ce4e35-7652-4a1c-a192-8477e149e832",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "74e9a556-d194-48ac-b0fd-ef3c192c2031",
        "measures": [
          {
            "name": "InvoiceSum",
            "expression": "SUM('Monitoring Invoice'[Invoiced DKK - monthly])",
            "formatString": "0",
            "lineageTag": "c6300606-9b5a-4a11-94e2-63779d47ca21"
          },
          {
            "name": "InvoiceLoadedSum",
            "expression": "sum([InvoiceLoaded])",
            "formatString": "#,0",
            "lineageTag": "83d64b22-4082-40e6-b6da-1e3109c47a24"
          },
          {
            "name": "ForecastLoadedSum",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM('Monitoring Invoice'[ForecastLoaded])",
            "lineageTag": "efed1de0-859c-4bef-b401-b06191e7a7c5"
          },
          {
            "name": "ForecastLoadedResult",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[InvoiceLoadedSum] - [ForecastLoadedSum]",
            "lineageTag": "19ccbff9-2d85-489f-b91f-85bcb57afe13"
          },
          {
            "name": "ForecastLoadedResultPerc",
            "expression": "[ForecastLoadedResult] / [InvoiceLoadedSum]",
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "a18c68c3-e740-437d-a5f7-536d8b473688"
          },
          {
            "name": "LastMonthLoadedSum",
            "expression": "sum('Monitoring Invoice'[LastMonthLoaded])",
            "formatString": "#,0",
            "lineageTag": "721d76f0-7d2e-472f-8463-a2de7fc01f0e"
          },
          {
            "name": "LastMonthLoadedResult",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    [InvoiceLoadedSum] - [LastMonthLoadedSum]"
            ],
            "lineageTag": "5573a1e6-6b4c-4439-b3b3-8701a377a782"
          },
          {
            "name": "LastMonthLoadedResultPerc",
            "expression": "[LastMonthLoadedResult] / [InvoiceLoadedSum]",
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "f9b2c51c-6e8d-4d6e-892c-d468c9cc9ac5"
          },
          {
            "name": "InvoiceCost%",
            "expression": "[LastMonthLoadedSum] / [InvoiceLoadedSum]",
            "formatString": "0.0\\ %;-0.0\\ %;0.0\\ %",
            "lineageTag": "64bbcb81-963d-4889-8850-8969457aa6ae"
          },
          {
            "name": "TwoMonthResult",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "([LastMonthLoadedResult] + [ForecastLoadedResult]) / 2",
            "lineageTag": "e76a8bb5-b8ee-46f6-aba3-98ff3dcc34d6"
          },
          {
            "name": "TwoMonthResult%",
            "expression": "([LastMonthLoadedResultPerc] + [ForecastLoadedResultPerc]) / 2",
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "f4439108-7fd7-40eb-9efe-cf83f9d7e7c3"
          },
          {
            "name": "ForecastLResultNegative",
            "lineageTag": "d3da222a-b228-4f76-90ee-2a918a9f2f27"
          },
          {
            "name": "ForecastLoadedCriticalAmount",
            "expression": [
              "--Counts the # of solutions in critical are (result below 5%)",
              "CALCULATE(",
              "    COUNT('Monitoring Invoice'[ForecastLoadedResultPercCol]), ",
              "    'Monitoring Invoice'[ForecastLoadedResultPercCol]<0.05)"
            ],
            "formatString": "0",
            "lineageTag": "f6f513ba-b3ae-42ef-9ae9-4d4c9dc9a462"
          },
          {
            "name": "ForecastLoadedWarningAmount",
            "expression": [
              "--Calculate # of solutions in the risk zone (result between 5-15%)",
              "CALCULATE(",
              "    COUNT('Monitoring Invoice'[ForecastLoadedResultPercCol]),",
              "    'Monitoring Invoice'[ForecastLoadedResultPercCol] > 0.05,",
              "    'Monitoring Invoice'[ForecastLoadedResultPercCol] < 0.15",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "2f151a8a-8e2f-476d-93c5-b0ac7c24c500"
          },
          {
            "name": "MoMChange",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[MW_MostConsumptionEOM_Forecast] - [MW_MostConsumptionLM]",
            "lineageTag": "4fab49de-096f-44b8-9988-2088680b3c80"
          },
          {
            "name": "MoMChange%",
            "expression": [
              "IF(",
              "    OR(",
              "        ISBLANK([MW_MostConsumptionEOM_Forecast]), ",
              "        ISBLANK([MW_MostConsumptionLM])",
              "    ), ",
              "    BLANK(), ",
              "    ([MW_MostConsumptionEOM_Forecast] - [MW_MostConsumptionLM]) / [MW_MostConsumptionLM]",
              ")",
              ""
            ],
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "6c9223ea-9338-406d-bdbc-fe04fe865cbd"
          }
        ],
        "partitions": [
          {
            "name": "Monitoring Invoice",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(Web.Contents(Invoice_Input), null, true),",
                "    Invoicing_Table = Source{[Item=\"Tabel1\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Invoicing_Table,{{\"SolutionID\", Int64.Type}, {\"SolutionFriendlyName\", type text}, {\"Client\", type text}, {\"Invoiced DKK - monthly\", Int64.Type}, {\"Update Date\", type date}, {\"Update Author\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_c3b27cf4-d733-487e-92d7-690a71a60449",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "7e6dbe7c-58d1-4d69-b943-a5d0d8df18d9",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "36693ff3-ce25-4431-a0dc-7dbdb1ad2a49",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "7c7a9060-6e0a-4723-b687-3a6c5e39a480",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "b34877e7-9acb-4436-a9b2-c3bf5812bcfe",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "9d133dec-d2dc-488b-b8e4-1fe07599fa98",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "dcecac51-c80b-42a6-a03f-4d74cdce28c1",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "57de036a-fff6-423b-acce-4f1efaf78b13",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "7a26515c-0a77-4a0d-8930-317cb77c9279",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "2aa07bfb-f858-4288-85df-cd15d2b10bcb",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "352e7486-2f94-4b70-afbc-872dd7984a32",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "b549b173-d4d5-4a70-a260-b984547df9eb",
                "ordinal": 3
              }
            ],
            "lineageTag": "4ff16d9a-eb61-4b2c-81c3-2122dc5aaccd"
          }
        ],
        "isHidden": true,
        "lineageTag": "b4e44ff6-16c0-4ff9-8700-7590e28c8987",
        "partitions": [
          {
            "name": "LocalDateTable_c3b27cf4-d733-487e-92d7-690a71a60449",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Monitoring Invoice'[Update Date])), 1, 1), Date(Year(MAX('Monitoring Invoice'[Update Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}